#!/usr/bin/env python3

import os
import re
from PyPDF2 import PdfMerger

pdfs = os.listdir(os.path.dirname(__file__))
pdfs = [re.search(r'(kz-plot-(\d+).pdf)', pdf) for pdf in pdfs]
pdfs = sorted((m.groups() for m in pdfs if m), key=lambda x: int(x[1]))
pdfs = [pdf[0] for pdf in pdfs]
print(*pdfs, sep='\n')

merger = PdfMerger()
for pdf in pdfs:
    merger.append(pdf)
merger.write('kz-plot.pdf')
